/**
 * Generated by orval v6.30.2 🍺
 * Do not edit manually.
 * Web開発研修6班 API
 * FY24卒Web開発研修6班のAPI仕様書です
 * OpenAPI spec version: 1.0.0
 */

export * from './schemaCommentResponse';
export * from './schemaCreateCommentRequest';
export * from './schemaCreatePostRequest';
export * from './schemaErrorResponse';
export * from './schemaLoginRequest';
export * from './schemaMutationSchema';
export * from './schemaPostResponse';
export * from './schemaUpdateCommentRequest';
export * from './schemaUpdatePostRequest';
export * from './schemaUserResponse';