/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * Web開発研修 API
 * FY24卒Web開発研修6班のAPI仕様書です。

 * OpenAPI spec version: 1.0.0
 */

/**
 * 投稿のモデル
 */
export interface Post {
  body?: string;
  created_at: string;
  id: number;
  title: string;
  updated_at?: string;
  user_id: number;
  user_name: string;
}
export interface CreatePost {
  body?: string;
  title: string;
}
