/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * Web開発研修6班 API
 * FY24卒Web開発研修6班のAPI仕様書です
 * OpenAPI spec version: 1.0.0
 */

export interface SchemaUpdateCommentRequest {
  body?: string;
}
