/**
 * Generated by orval v6.30.2 🍺
 * Do not edit manually.
 * Web開発研修6班 API
 * FY24卒Web開発研修6班のAPI仕様書です
 * OpenAPI spec version: 1.0.0
 */

export interface SchemaPostResponse {
  body?: string
  post_id?: number
  title?: string
  user_id?: number
  user_name?: string
}
